/** @type {import('@storybook/react-vite').StorybookConfig} */
module.exports = {
  stories: ['../src/**/*.stories.@(ts|tsx|js|jsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-a11y',  // 来自 prototype-validator 思路
    '@storybook/addon-themes',
  ],
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },
  docs: { autodocs: 'tag' },
  typescript: { check: false, reactDocgen: 'react-docgen-typescript' },
};

// Auto-generated by storybook-chromatic skill.
