#!/usr/bin/env python3
"""generate_swift.py - tokens → Swift Tokens.swift"""

import argparse
import json
import re
from pathlib import Path


def flatten(obj, prefix=""):
    out = []
    for k, v in obj.items():
        path = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            out.extend(flatten(v, path))
        else:
            out.append((path, v))
    return out


def to_swift_name(path: str) -> str:
    parts = path.split(".")
    camel = parts[0] + "".join(p.title() for p in parts[1:])
    return camel


def hex_to_swift(hex_color: str) -> str:
    h = hex_color.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    r, g, b = h[0:2], h[2:4], h[4:6]
    a = h[6:8] if len(h) == 8 else "FF"
    return f"Color(red: 0x{r}/255, green: 0x{g}/255, blue: 0x{b}/255, opacity: 0x{a}/255)"


def to_swift_value(path: str, val) -> str:
    s = str(val)
    if re.match(r"^#[0-9A-Fa-f]{3,8}$", s):
        return hex_to_swift(s)
    if re.match(r"^[\d.]+px$", s):
        n = s.replace("px", "")
        return f"CGFloat({n})"
    if re.match(r"^[\d.]+ms$", s):
        n = s.replace("ms", "")
        return f"{n} / 1000.0"
    if re.match(r"^[\d.]+$", s):
        return s
    return f'"{s}"'


def main():
    parser = argparse.ArgumentParser(description="生成 Swift Tokens")
    parser.add_argument("--tokens", required=True)
    parser.add_argument("--output", "-o", required=True)
    args = parser.parse_args()

    tokens = json.loads(Path(args.tokens).read_text(encoding="utf-8"))

    lines = [
        "// Auto-generated by ui-design-system",
        "import SwiftUI",
        "",
        "public enum Tokens {",
    ]

    for category in ["color", "font", "space", "radius", "shadow", "motion"]:
        if category not in tokens:
            continue
        lines.append(f"    public enum {category.title()} {{")
        for path, val in flatten({category: tokens[category]}):
            key = path.split(".", 1)[1] if "." in path else path
            name = to_swift_name(key)
            swift_val = to_swift_value(path, val)
            lines.append(f"        public static let {name} = {swift_val}")
        lines.append("    }")

    lines.append("}")
    lines.append("")

    Path(args.output).write_text("\n".join(lines), encoding="utf-8")
    print(f"✅ 已生成: {args.output}")


if __name__ == "__main__":
    main()
